
############## 安装时基础信息 #############################
# 定义zabbix安装版本，启动用户，安装路径，包路径
ZABBIX_VER: 4.2.1
RUN_USER: zabbix
PACKAGE_DIR: /opt/aspire/product/package
BASE_DIR: /opt/aspire/product/zabbixpxy

######## zabbix agentd/zabbix proxy 通用配置 ###############
LOG_FILE: /tmp
PID_FILE: /tmp

############### 数据库连接信息 #####################
DB_ROOT: root
DB_ROOTPASS: Qazwsx@1234
DB_PORT: 3306
DB_HOST: localhost

# ############## zabbix proxy 相关信息配置 #####################
# # zabbix数据库信息
DB_NAME: zabbix_proxy
DB_USER: zabbix
DB_PASSWORD: Asp@aspire+999
SERVER: 127.0.0.1
SERVER_PORT: 10051
HOSTNAME: zabbix_proxy
LISTEN_PORT: 10051

# ############## zabbix agent 相关信息配置 #####################
AGENT_SERVER: 127.0.0.1
AGENT_LISTEN_PORT: 10052


############## zabbix proxy参数默认配置 ######################
StartPollers: 20
StartPreprocessors: 20
StartPollersUnreachable: 20
StartTrappers: 20
StartPingers: 20
CacheSize: 1G
HistoryCacheSize: 1G
HistoryIndexCacheSize: 1G
Timeout: 30
FpingLocation: /usr/sbin/fping
