---

# 该节点下ip安装mysql
- name: install mysql for hosts
  hosts: mysql
  remote_user: root
  gather_facts: false
  roles:
    # the role  for mysql install and init first time
    - role: mysql_install

# # 该节点下安装zabbix_proxy
# - name: install zabbix_proxy for hosts
#   hosts: zabbix_proxy
#   remote_user: root
#   gather_facts: false
#   roles:
#     - role: zabbix_proxy

# #安装ops
# - name: install ops for hosts
#   hosts: ops
#   remote_user: root
#   gather_facts: false
#   roles:
#     - role: ops